alias rspec="rspec -c"
alias turn_screen_off="sleep 1 ; xset dpms force off"
alias gc="git commit"
alias gp="git push"
alias gs="git status"
alias ga="git add"
alias lampp_server="sudo /opt/lampp/manager-linux-x64.run"
alias android_studio="~/Android/bin/studio.sh"
